### ISSUE TITLE
Not installing on Laravel 7.4

### ISSUE THREAD

**Issue by rjacomel** [matriphe/larinfo#11]
Could you please release to Laravel 7?

` composer require matriphe/larinfo
Using version ^2.0 for matriphe/larinfo
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for matriphe/larinfo ^2.0 -> satisfiable by matriphe/larinfo[2.0].
    - Conclusion: remove laravel/framework v7.4.0
    - Conclusion: don't install laravel/framework v7.4.0
    - matriphe/larinfo 2.0 requires laravel/framework ^5.0 | ^6.0 -> satisfiable by laravel/framework[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, 6.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.6.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.7.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.8.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[6.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.0.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.1.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.2.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.3.x-dev, v7.4.0].
    - Can only install one of: laravel/framework[5.4.x-dev, v7.4.0].
    - Installation request for laravel/framework (locked at v7.4.0, required as ^7.3) -> satisfiable by laravel/framework[v7.4.0].

Installation failed, reverting ./composer.json to its original content.`

**Comment by matriphe** [comment]
It's solved in #12
