### ISSUE TITLE
PHP8 Support

### ISSUE THREAD

**Issue by repat** [matriphe/larinfo#22]
Hi @matriphe,

could you update the composer.json to say `"php": "^7.1 | ^8.0",`. That way I can upgrade my applications to use PHP8 :)

Thanks!

**Comment by matriphe** [comment]
Hi, thanks for reporting. You can create a pull request for this as well!

**Comment by repat** [comment]
Sure, but I can't do this for every project where the maintainer doesn't do it, that would take up most of my day ;)

**Comment by repat** [comment]
Nevermind, uninstalled package + pulled in sourcecode directly.
