### ISSUE TITLE
Not working with Fedora Server

### ISSUE THREAD

**Issue by drewbdennis** [matriphe/larinfo#3]
I don't know if you have tested https://github.com/matriphe/larinfo by running it on a fedora server, but it doesn't seem to be working for me. Rather the page continue loading forever. And the sad part, the code isn't producing any kind of error for me to even debug.

**Comment by matriphe** [comment]
What version Fedora or PHP do you use?

**Comment by drewbdennis** [comment]
Fedora Server 26 and php 7.1

**Comment by matriphe** [comment]
There's a unresolved (yet) bug in the linfo library on PHP 7.1. Please refer to this issue: https://github.com/jrgp/linfo/issues/53

**Comment by drewbdennis** [comment]
Then that is strange because it runs fine in fedora 26 desktop edition
running the same version of php 7.1

**Comment by matriphe** [comment]
The problem is in the opcache extension on PHP 7.1. Do you use it (loaded) in the Fedora Server? If it's so, try to disable it via `php.ini` and see if that's work.

**Comment by drewbdennis** [comment]
I will give that a try. Thanks for the help.

Best Regards,
Drew B. Dennis

The quieter you become, the more you can hear. - Ram Dass

**Comment by matriphe** [comment]
Sure, no problem! Let me know if that's working.

**Comment by drewbdennis** [comment]
Hi,

Thanks for the help. I managed to disable it from this location
/etc/php.d/10-opcache.ini

Best Regards,
Drew B. Dennis

The quieter you become, the more you can hear. - Ram Dass

**Comment by drewbdennis** [comment]
To solve the problem in Fedora Server 26, I disable opcache which was located at this location /etc/php.d/10-opcache.ini

**Comment by jrgp** [comment]
FYI this was caused by https://bugs.php.net/bug.php?id=75255 which newer versions of php7.1 fixed (and fedora has included the newer versions of php in fedora26, so updating packages should fix)
