### ISSUE TITLE
Non-static method Matriphe\Larinfo\Larinfo::getInfo() should not be called statically

### ISSUE THREAD

**Issue by eugenevdm** [matriphe/larinfo#4]
Getting above error on Laravel 5.5. Any clues? Also seems to be documented on Stack Exchange:

https://stackoverflow.com/questions/46186587/using-matriphe-larinfo-on-laravel-5-4-project-getting-class-not-found-error

**Comment by matriphe** [comment]
Hello, can you provide me the version of PHP do you use? If you're using PHP versio 7.1, please make sure you disable opcache.

**Comment by jdelacruz2712** [comment]
I have to problem !

![image](https://user-images.githubusercontent.com/7109723/35237752-9a3b717e-ff79-11e7-9dca-cecb50d61264.png)

![image](https://user-images.githubusercontent.com/7109723/35237767-a54dad98-ff79-11e7-89be-7e355d825b26.png)

**Comment by jdelacruz2712** [comment]
**Solution ?**

**Comment by matriphe** [comment]
Hello,

Sorry for the late reply.

Could you provide me with PHP version or Laravel version do you use?

-- 
Muhammad Zamroni
Sent with Airmail

On 8 February 2018 at 11.41.38, Jeancarlos De la Cruz Criollo (
notifications@github.com) wrote:

*Solution ?*

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/matriphe/larinfo/issues/4#issuecomment-364000751>, or mute
the thread

**Comment by jdelacruz2712** [comment]
Not problem my friend, used laravel 5.5.

**Comment by matriphe** [comment]
What version of PHP do you use? Do you have opcache enabled?

**Comment by jdelacruz2712** [comment]
Hi, opcache enabled 

![image](https://user-images.githubusercontent.com/7109723/35987656-470c8160-0cca-11e8-8ede-5c5f3c56a8ce.png)


Version php : 7.2

**Comment by matriphe** [comment]
Thanks! I will check it, soon!

**Comment by jdelacruz2712** [comment]
Thanks my friend 😄

**Comment by matriphe** [comment]
@jdelacruz2712 sorry for very late response.

have you try disabling the Opcache. it's because since version 7.1 the library has unsolved bug in opcache.

please refer the issue here https://github.com/jrgp/linfo/issues/53

let see if disabling opcache wil resolve the problem.

**Comment by jrgp** [comment]
I don't think the opcache bug would cause this bug as it's a syntactic/class usage bug and the opcache issue just makes the php interpreter hang forever.

**Comment by jrgp** [comment]
I just looked through the larevel linfo code, and running `Larinfo::getServerInfo()` (in the usage screenshot in the first post) is not going to work because that method is not defined as `static` and it heavily utilizes `$this->` which does not exist in a static context.

**Comment by matriphe** [comment]
Ah, I figure it out. I think @jdelacruz2712 not using the Facade but directly using the class.

You don't need to load the `Matriphe\Linfo\Linfo`, but can directly use the facade `Larinfo`.

Just change the `use Matriphe\Larinfo\Larinfo` to `use Larinfo`

Sorry I didn't notice it.
