### ISSUE TITLE
Method getVirtualization not present 

### ISSUE THREAD

**Issue by imdeepakchahar** [matriphe/larinfo#5]
when i use 
```
use Larinfo;
class SettingsController extends Controller
{
public function index()
    {
        $larinfo = Larinfo::getHostIpinfo();
        $larinfosoftware = Larinfo::getServerInfoSoftware();
        $larinfohardware = Larinfo::getServerInfoHardware();
        $larinforam = Larinfo::getServerInfo();
        $larinfouptime = Larinfo::getUptime();
        $larinfodb = Larinfo::getDatabaseInfo();
}
}
```
Then error shown **Method getVirtualization not present**
```
$virtualization = $this->getVirtualizationString(
            $this->ifExists($linfo->getVirtualization())
        );
``` 
@matriphe  please solve it #5  #

**Comment by pschilly** [comment]
Has this been solved?

**Comment by snehal-ent** [comment]
I got the same issue.. is it related to virtualization support of the device??
because I use Windows 10 and AMD chipset where chipset supports it but ACER bios have not given an update regarding it...

**Comment by Snehal-Gajjar** [comment]
I got the same issue.. is it related to virtualization support of the device??
because I use Windows 10 and AMD chipset where chipset supports it but ACER bios have not given an update regarding it...

**Comment by Snehal-Gajjar** [comment]
i had added this code in vendor\linfo\linfo\src\Linfo\OS\Windows.php

public function getVirtualization()
     {

        // Time?
        if (!empty($this->settings['timer'])) {
            $t = new Timer('Determining virtualization type');
        }

        // OpenVZ host?
        if (is_file('/proc/vz/version')) {
            return array('type' => 'host', 'method' => 'OpenVZ');
        }

        // OpenVZ guest?
        elseif (is_file('/proc/vz/veinfo')) {
            return array('type' => 'guest', 'method' => 'OpenVZ');
        }

        // Veertu guest?
        if (Common::getContents('/sys/devices/virtual/dmi/id/bios_vendor') == 'Veertu') {
            return array('type' => 'guest', 'method' => 'Veertu');
        }

	// LXC guest?
        if (strpos(Common::getContents('/proc/mounts'), 'lxcfs /proc/') !== false) {
            return array('type' => 'guest', 'method' => 'LXC');
        }

        // Docker guest?
        if (is_file('/.dockerenv') || is_file('/.dockerinit') || strpos(Common::getContents('/proc/1/cgroup'), 'docker') !== false) {
            return array('type' => 'guest', 'method' => 'Docker');
        }

        // Try getting kernel modules
        $modules = [];
         if (preg_match_all('/^(\S+)/m', Common::getContents('/proc/modules', ''), $matches, PREG_SET_ORDER)) {
             foreach ($matches as $match) {
                 $modules[] = $match[1];
             }
         }

        // Sometimes /proc/modules is missing what is in this dir on VMs
        foreach (@glob('/sys/bus/pci/drivers/*') as $name) {
                $modules[] = basename($name);
        }

        // VMware guest. Tested on debian under vmware fusion for mac...
        if (Common::anyInArray(array('vmw_balloon', 'vmwgfx', 'vmw_vmci'), $modules)) {
            return array('type' => 'guest', 'method' => 'VMWare');
        }

        // VMware Host! tested on rhel6 running vmware..workstation?
        if (Common::anyInArray(array('vmnet', 'vmci', 'vmmon'), $modules)) {
            return array('type' => 'host', 'method' => 'VMWare');
        }

        // Looks like it might be xen...
        if (Common::anyInArray(array('xenfs', 'xen_gntdev', 'xen_evtchn', 'xen_blkfront', 'xen_netfront'), $modules) || is_dir('/proc/xen')) {

            // Guest or host?
            if (Common::anyInArray(array('xen-netback', 'xen_blkback'), $modules) || strpos(Common::getContents('/proc/xen/capabilities', ''), 'control_d') !== false) {
                return array('type' => 'host', 'method' => 'Xen');
            } else {
                return array('type' => 'guest', 'method' => 'Xen');
            }
        }

        // VirtualBox Host! Tested on lucid running vbox..
        if (in_array('vboxdrv', $modules)) {
            return array('type' => 'host', 'method' => 'VirtualBox');
        }

        // VirtualBox Guest! Tested on wheezy under mac vbox
        if (in_array('vboxguest', $modules)) {
            return array('type' => 'guest', 'method' => 'VirtualBox');
        }

        // Hyper-V guest. Tested with Trusty under Client Hyper-V in Windows 10 Pro. Needs to be checked before KVM/QEMU!
        if (Common::anyInArray(array('hid_hyperv', 'hv_vmbus', 'hv_utils'), $modules)) {
            return array('type' => 'guest', 'method' => 'Hyper-V');
        }

        // Looks like it might be KVM HOST!
        if (Common::anyInArray(array('kvm_intel', 'kvm_amd'), $modules)) {
            return array('type' => 'host', 'method' => 'KVM');
        }

        // Looks like it might be a KVM or QEMU guest! This is a bit lame since Xen can also use virtio but its less likely (?)
        if (Common::anyInArray(array('virtio', 'virtio_balloon', 'virtio_pci', 'virtio-pci', 'virtio_blk', 'virtio_net'), $modules)) {
            return array('type' => 'guest', 'method' => 'Qemu/KVM');
        }

        // idk
        return false;
     }

and I got solved virtualization error but I got swap memory error so I solved it by editing this function as ...

public function getRam()
    {

        // Time?
        if (!empty($this->settings['timer'])) {
            $t = new Timer('Memory');
        }

        $total_memory = 0;
        $free_memory = 0;

        foreach ($this->wmi->ExecQuery('SELECT TotalPhysicalMemory FROM Win32_ComputerSystem') as $cs) {
            $total_memory = $cs->TotalPhysicalMemory;
            break;
        }

        foreach ($this->wmi->ExecQuery('SELECT FreePhysicalMemory FROM Win32_OperatingSystem') as $os) {
            $free_memory = $os->FreePhysicalMemory;
            break;
        }

        return array(
            'type' => 'Physical',
            'total' => $total_memory,
            'free' => $free_memory * 1024,
            'swapTotal' => 0,
            'swapFree' => 0,
        );
    }

**Comment by matriphe** [comment]
it would be great if you can create a PR for this functionality, since I don't have Windows machine.

**Comment by Snehal-Gajjar** [comment]
I need to discuss few things on this where I can contact you?

**Comment by matriphe** [comment]
we can discuss it here

**Comment by Snehal-Gajjar** [comment]
Ok, so I used your code to fix the error as a temporary patch... I don't know is it goof or not but it's working.
N I think virtulization method must not to be mandatory in case of operating system varies over different platforms n devices.. n another point I got about swap memory is not exist over application level access in windows... So no use of it... It will require kernel level access.....
Another few things I want to discuss for business... If you would like to add me in LinkedIn.

**Comment by matriphe** [comment]
yes, it might need to refactor and change some methods. it’s a good idea to
not make virtualization mandatory.


regarding swap memory, in Windows, there’s no such that thing.


you can contact me through e-mail in my Github profile.


On 28. May 2020 at 22:53:05, Snehal Gajjar (notifications@github.com) wrote:

Ok, so I used your code to fix the error as a temporary patch... I don't
know is it goof or not but it's working.
N I think virtulization method must not to be mandatory in case of
operating system varies over different platforms n devices.. n another
point I got about swap memory is not exist over application level access in
windows... So no use of it... It will require kernel level access.....
Another few things I want to discuss for business... If you would like to
add me in LinkedIn.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matriphe/larinfo/issues/5#issuecomment-635601541>, or
unsubscribe

**Comment by matriphe** [comment]
Please check the latest release 3.0. I hope it helps. Closing it for now. If you have any issue, you can reopen this.
