### ISSUE TITLE
Update to Laravel 6

### ISSUE THREAD

**Issue by repat** [matriphe/larinfo#6]
Could you release a version for Laravel 6 please? :-)

**Comment by repat** [comment]
https://github.com/matriphe/larinfo/pull/7

**Comment by repat** [comment]
Thank you!

**Comment by repat** [comment]
https://packagist.org/packages/matriphe/larinfo

packagist doesn't seem to get the new version 🤔 @matriphe

**Comment by matriphe** [comment]
@repat there was a problem with Github Webhook. The issue has been solved.
